### ISSUE TITLE
Include work/alpha/beta/rc tarballs

### ISSUE THREAD

**Issue by craigbarnes** [lua/repogen#1]
As [mentioned](https://github.com/lua/lua/pull/4#issuecomment-92108951) by @hishamhm, it would be good to include pre-release stuff from http://www.lua.org/work/old/index.htm between the major releases.

**Comment by craigbarnes** [comment]
Issues so far:

* The `lua-5.1-rc1.tar.gz` tarball unpacks to a directory named `lua-5.1`, which needs to be renamed to `lua-5.1-rc1` and may clobber the state of the working directory.
* The tarball at http://www.lua.org/work/old/lua-5.2.0-alpha-rc3.tar.gz returns `403 Forbidden`.

**Comment by craigbarnes** [comment]
All `lua-5.1-*` tarballs are included as of 26254fb. The rest are [`TODO`](https://github.com/lua/repogen/blob/26254fbbb8019440f218115599d49bf5714b732c/graph.mk#L68-134)

**Comment by craigbarnes** [comment]
I've added a few of the alpha/beta/rc versions to the repogen scripts. The following are still left to do:

- [ ] 5.2.4-rc1
- [ ] 5.2.3-rc1
- [ ] 5.2.2-rc4
- [ ] 5.2.2-rc3
- [ ] 5.2.2-rc2
- [ ] 5.2.2-rc1
- [ ] 5.2.1-rc4
- [ ] 5.2.1-rc3
- [ ] 5.2.1-rc2
- [ ] 5.2.1-rc1
- [ ] 5.2.1-work1
- [ ] 5.1.5-rc2
- [ ] 5.1.5-rc1
- [ ] 5.2.0-rc8
- [ ] 5.2.0-rc7
- [ ] 5.2.0-rc6
- [ ] 5.2.0-rc5
- [ ] 5.2.0-rc4
- [ ] 5.2.0-rc3
- [ ] 5.2.0-rc2
- [ ] 5.2.0-rc1
- [ ] 5.2.0-beta
- [ ] 5.2.0-beta-rc7
- [ ] 5.2.0-beta-rc6
- [ ] 5.2.0-beta-rc5
- [ ] 5.2.0-beta-rc4
- [ ] 5.2.0-beta-rc3
- [ ] 5.2.0-beta-rc2
- [ ] 5.2.0-beta-rc1
- [ ] 5.2.0-alpha
- [ ] 5.2.0-alpha-rc4
- [ ] **5.2.0-alpha-rc3**
- [ ] 5.2.0-alpha-rc2
- [ ] 5.2.0-alpha-rc1
- [ ] 5.2.0-work5
- [ ] 5.2.0-work4
- [ ] 5.2.0-work3
- [ ] 5.2.0-work2
- [ ] 5.2.0-work1

Unfortunately `5.2.0-alpha-rc3` is right in the middle of a series of pre-releases and the [tarball][5.2.0-alpha-rc3] on lua.org is currently returning a `403 Forbidden` error.


[5.2.0-alpha-rc3]: http://www.lua.org/work/old/lua-5.2.0-alpha-rc3.tar.gz

**Comment by hishamhm** [comment]
The 403 is most likely a matter of running `chmod +x` in the server. We
could ask lhf about it.

**Comment by hishamhm** [comment]
I meant `chmod +r`, of course. I just emailed lhf about it!

**Comment by craigbarnes** [comment]
@hishamhm Thanks!

**Comment by hishamhm** [comment]
lhf just emailed me back, it should be fixed now!

**Comment by craigbarnes** [comment]
Thanks for the help (and to lhf for the quick fix)!

All the releases on `master` are handled and pushed to [github.com/lua/lua](https://github.com/lua/lua) now. There's just the 3 branches left to do:

- [ ] 5.2.3-rc1 -> 5.2.4 (branched at 5.2.2)
- [ ] 5.1.5-rc1 -> 5.1.5 (branched at 5.1.4)
- [ ] 5.0.3 (branched at 5.0.2)
