### ISSUE TITLE
Generate a repository for the Lua test suites

### ISSUE THREAD

**Issue by neico** [lua/repogen#4]
Sinc the tests repo has no issue tracker I'll post this here.

The repo needs an update as it for example contains some errors which makes the entire suite fail at various points (which isn't something that should happen on a test suite)

PS: looks like the repo itself isn't being managed by the repogen yet, so that's probably something else to consider

**Comment by craigbarnes** [comment]
I've deleted the `tests` repo for now, since it was just a mess of manual commits and not much more than a placeholder. I'll update `repogen` to also generate the `tests` repo when I get time.

**Comment by craigbarnes** [comment]
There's another effort in the works that will eventually make repogen redundant, so I'm not going to work on it any more (except for adding new Lua releases in the meantime).

**Comment by neico** [comment]
Sounds promising, can't wait to see the results

**Comment by craigbarnes** [comment]
@neico Just in case you haven't seen it already, there's now a repo for the test suite at https://github.com/lua/tests

**Comment by neico** [comment]
Yeah I noticed when there was the announcement around the LuaWorkshop talk
